### ISSUE TITLE
Wrong Segmentation Slices Position

### ISSUE THREAD

**Issue by benarnon8** [ImagingDataCommons/highdicom#117]
I'm writing a script to attach AI made lesion segmentations to existing DICOM files (It's my first time that I dive so deep into DICOM, so I might have missed something).

I have found your repository and used `hd.seg.Segmentation`, but unfortunately the order of the segmentation slices was incorrect.

First I tried to use just a dummy segmentation (simple 3D box over an MRI), and after encountering the issue I decided to try another approach:
I took an existing DICOM file (of a CT scan) that contains both a scan and a segmentation, converted the segmentation to np.array, and used is as the `mask` input, while the scan folder is the `source_images`.

From the original segmentation file (9 slices between -224.5mm to -192.5mm, 4mm thickness):
`(0020,0032) DS [-189.136\-320.136\-224.5]               #  24, 3 ImagePositionPatient`
`(0020,0032) DS [-189.136\-320.136\-220.5]               #  24, 3 ImagePositionPatient`
:
`(0020,0032) DS [-189.136\-320.136\-192.5]               #  24, 3 ImagePositionPatient`

Versions:
_Python 3.8.10
numpy 1.21.2
pydicom 2.2.1
highdicom 0.10.0_

Code snippets:
```
:

# Collection the scan images
image_datasets = [dcmread(str(f)) for f in image_files]

# Creating a segmentation mask from the existing segmentation. shape = (108, 512, 512)
mask = np.zeros(
    shape=(
        len(image_datasets),
        image_datasets[0].Rows,
        image_datasets[0].Columns
    ),
    dtype=bool
)
mask[86:95, :, :] = np.array(hd.seg.segread(
    '/home/ben/.../original_seg.dcm'
    ).pixel_array, dtype=bool)

# Printing to check if the order is correct
sl_num = -568.5
for slice in mask:
    print(sl_num, np.unique(slice))
    sl_num += 4
```

Output:
```
-568.5 [False]
-564.5 [False]
-560.5 [False]
:
-236.5 [False]
-232.5 [False]
-228.5 [False]
-224.5 [False  True]
-220.5 [False  True]
-216.5 [False  True]
-212.5 [False  True]
-208.5 [False  True]
-204.5 [False  True]
-200.5 [False  True]
-196.5 [False  True]
-192.5 [False  True]
-188.5 [False]
-184.5 [False]
-180.5 [False]
:
-148.5 [False]
-144.5 [False]
-140.5 [False]
```

Creating the segmentation:

```
# Get meta-data information from the existing series
series_instance_uid = image_datasets[0].SeriesInstanceUID
series_number = image_datasets[0].SeriesNumber
sop_instance_uid = image_datasets[0].SOPInstanceUID
instance_number = image_datasets[0].InstanceNumber
MANUFACTURER = 'Ben' # image_datasets[0].Manufacturer
MANUFACTURER_MODEL_NAME = "Prost" # image_datasets[0].ManufacturersModelName
SOFTWARE_VERSIONS = 'v1.0'
DEVICE_SERIAL_NUMBER = '0' # image_datasets[0].DeviceSerialNumber

# Describe the algorithm that created the segmentation family:
# http://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_CID_7162.html
algorithm_identification = hd.AlgorithmIdentificationSequence(
    name=MANUFACTURER_MODEL_NAME,
    version=SOFTWARE_VERSIONS,
    family=codes.cid7162.ArtificialIntelligence
)

# Describe the segment:
# https://highdicom.readthedocs.io/en/latest/package.html#highdicom.seg.SegmentDescription
# segmented_property_category:
# http://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_CID_7150.html
# segmented_property_type:
# http://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_CID_7160.html
description_segment = hd.seg.SegmentDescription(
    segment_number=1,
    segment_label='Lesions',
    segmented_property_category=codes.cid7150.AnatomicalStructure,
    segmented_property_type=codes.cid7160.Prostate,
    algorithm_type=hd.seg.SegmentAlgorithmTypeValues.AUTOMATIC,
    algorithm_identification=algorithm_identification,
    tracking_uid=hd.UID(),
    tracking_id='Lesion Segmentation of a Prostate MR Image',
    # anatomic_regions=Code("41216001", "SCT", "Prostate"), # BA - error, seems like the others are enough
)

# Create the Segmentation instance
# https://highdicom.readthedocs.io/en/latest/package.html#highdicom.seg.Segmentation
seg_dataset = hd.seg.Segmentation(
    source_images=image_datasets,
    pixel_array=mask,
    segmentation_type=hd.seg.SegmentationTypeValues.BINARY, # FRACTIONAL,
    segment_descriptions=[description_segment],
    series_instance_uid=series_instance_uid, # hd.UID(),
    series_number=series_number,
    sop_instance_uid=sop_instance_uid, # hd.UID(),
    instance_number=instance_number,
    manufacturer=MANUFACTURER,
    manufacturer_model_name=MANUFACTURER_MODEL_NAME,
    software_versions=SOFTWARE_VERSIONS,
    device_serial_number=DEVICE_SERIAL_NUMBER,
    omit_empty_frames=True,
    # content_creator_name=manufacturer,
)


# Compare generated and original segmentations
print('seg:')
for i, slice in enumerate(seg_dataset.PerFrameFunctionalGroupsSequence):
    print(float(str(slice['PlanePositionSequence']._value[0])[-7:-1]), np.unique(seg_dataset.pixel_array[i]))

ref_path = '/home/ben/.../original_seg.dcm'
ref_seg = hd.seg.segread(ref_path)
print('\noriginal:')
for i, slice in enumerate(ref_seg.PerFrameFunctionalGroupsSequence):
    print(float(str(slice['PlanePositionSequence']._value[0])[-7:-1]), np.unique(ref_seg.pixel_array[i]))
```

And the outputs:
```
seg:
-564.5 [0 1]
-552.5 [0 1]
-520.5 [0 1]
-488.5 [0 1]
-404.5 [0 1]
-328.5 [0 1]
-324.5 [0 1]
-244.5 [0 1]
-200.5 [0 1]

original:
-224.5 [0 1]
-220.5 [0 1]
-216.5 [0 1]
-212.5 [0 1]
-208.5 [0 1]
-204.5 [0 1]
-200.5 [0 1]
-196.5 [0 1]
-192.5 [0 1]
```

As seen, the newly generated segmentation got wrong `PlanePositionSequence`. The same happens when I use `omit_empty_frames=False`.

I'm still reading through the library source code, found another bug and told @hackermd about it but it was not related.

Had a thought about adding a _reorder by original position_ function, to make sure the segmentation is being mapped correctly in case the original scan files are not in order.

Any other thoughts or comments?

Many thanks to all of you anyway, it's a really impressive library and I'm glad you've released it exactly when I started working on this project :)

**Comment by hackermd** [comment]
Thanks for reporting the issue @benarnon8!

I will need to take a closer look, but am wondering whether you also tried setting `plane_positions` explicitly? The documentation of the `Segmentation` constructor states (see [highdicom.seg.Segmentation](https://highdicom.readthedocs.io/en/latest/package.html#highdicom.seg.Segmentation)):

> Position of each plane in pixel_array in the three-dimensional patient or slide coordinate space. If `None`, it will be assumed that the segmentation image has the same plane position as the source image(s). However, this will only work when the first dimension of pixel_array matches the number of frames in source_images (in case of multi-frame source images) or the number of source_images (in case of single-frame source images).

Are you sure that your approach of setting individual planes in `mask` (`mask[86:95, :, :] = ...`) is correct?

**Comment by hackermd** [comment]
I assigned @CPBridge who has extensive experience in creating segmentations of CT images.

**Comment by benarnon8** [comment]
> I will need to take a closer look, but am wondering whether you also tried setting `plane_positions` explicitly? The documentation of the `Segmentation` constructor states (see [highdicom.seg.Segmentation](https://highdicom.readthedocs.io/en/latest/package.html#highdicom.seg.Segmentation)):

I didn't manage to define it properly, also tried with `get_plane_positions_of_series` but my arguments were incorrect. Could you maybe show me an example for that?


> Are you sure that your approach of setting individual planes in `mask` (`mask[86:95, :, :] = ...`) is correct?

The locations and order of the "slices" of the mask are correct, that what I checked with the first output as the complete CT scan is from -568.5mm to -140.5mm.
If you ask about the concept then I'm not sure, I saw in your example that you just use np.array as a `pixel_array=mask` and the series as source `source_images=image_datasets`, so I created a mask that represents the original segmentation.

It is definitely possible that I did something wrong, just trying to understand what.


> I assigned @CPBridge who has extensive experience in creating segmentations of CT images.

Thank you! The final goal is to create a segmentation for MRI, are they defined in the same way?

**Comment by hackermd** [comment]
> > I will need to take a closer look, but am wondering whether you also tried setting plane_positions explicitly? The documentation of the Segmentation constructor states (see highdicom.seg.Segmentation):

> I didn't manage to define it properly, also tried with get_plane_positions_of_series but my arguments were incorrect. Could you maybe show me an example for that?

You will need to create an instance of `highdicom.PlanePositionSequence` for each segmentation image plane (`mask.shape[0]`):

```python
# X, Y, Z offsets of individual image frames in frame of reference
image_positions: List[Tuple[float, float, float]] = []
plane_positions = [
    hd.PlanePositionSequence(
        coordinate_system=hd.CoordinateSystemNames.PATIENT,
        image_position=(x, y, z)
    )
    for x, y, z in image_positions
]
```

**Comment by benarnon8** [comment]
Thanks, I'm on it and will update you if it works.

Meanwhile I've found out that the original image list is not ordered, and the locations where the segmentation should be are corresponding to the wrong positions that I got:

```
for i in range(86,95): 
    print(image_datasets[i]['ImagePositionPatient'][2])
```
```
-324.5
-552.5
-200.5
-404.5
-564.5
-488.5
-244.5
-520.5
-328.5
```

I'll try to write a function that orders the input scans anyway, as I think it'll be helpful and foolproof so users will not have to double check.

**Comment by CPBridge** [comment]
Hi @benarnon8, thanks for using the library and for taking the time to write a nice bug report. I am open minded to their being a bug in the library but I want to eliminate a few other possibilities first. Unfortunately the order of frames within the segmentation images is much more complicated than you might initially think. This is because the standard also supports things like slide microscopy images, which are drawn from tiles of a 2D space.

I suspect your issue is due to a mismatch in the order of the planes between the input CT series and whatever the pydicom `.pixel_array` returns. Unfortunately there's no reason at all to assume that these two would match. Instead of @hackermd 's approach, can you please try the following two steps (at the same time), and let me know whether this fixes your issue?

1. *Order the input frames*. Your input image frames may be out of order (depending on how you read in the images), could you please order them spatially using this function:

```python
from typing import List
import pydicom

def order_datasets(datasets: List[pydicom.Dataset]) -> List[pydicom.Dataset]:
    def calc_slice_distance(dataset: pydicom.Dataset) -> float:
        orientation = np.array(dataset.ImageOrientationPatient, dtype=float)
        position = np.array(dataset.ImagePositionPatient, dtype=float)
        normal = np.cross(orientation[0:3], orientation[3:6])
        return float(np.dot(normal, position))

    return sorted(datasets, key=calc_slice_distance)
```

2. Make sure the way you are reading frames from the segmentation image matches your list of input files. Due to the way order is defined within the segmentation standard, it's nearly always a bad idea to use pydicom's `.pixel_array` property to access the pixel data of a segmentation. Please use the highdicom method [get_pixels_by_source_instance](https://highdicom.readthedocs.io/en/latest/package.html?highlight=Segmentation#highdicom.seg.Segmentation.get_pixels_by_source_instance) like this to have highdicom figure this out for you and ensure that the two lists match:

```python
source_sop_instance_uids = [im.SOPInstanceUID for im in image_datasets]
mask = seg.get_pixels_by_source_instance(
    source_sop_instance_uids,
    assert_missing_frames_are_empty=True
)
``` 

This should return the full array of the mask, including all the empty frames (so you can remove the `mask[86:95, :, :]` line). I know that the documentation is lacking on this point currently and will hopefully improve it soon!

If you follow these two steps, the order of the frames in the mask and the source datasets should match and I think everything should work correctly. We'll find out!

I realise that this may not be possible, but would you be able to provide me with the set of files you are using, assuming that they are anonymised? That would help debugging immensely. Also, do you know what software created the segmentation you are reading?

**Comment by CPBridge** [comment]
> Had a thought about adding a reorder by original position function, to make sure the segmentation is being mapped correctly in case the original scan files are not in order.

In fact, this is already what the constructor does (my step 1 above is just to be on the safe side and eliminate a further source of confusion). However there is a big caveat: the order of the frames in the `pixel_array` parameter to the `Segmentation` constructor *must match* the order of instances in the `source_images` parameter. Unfortunately, I think this is the only sane way to do this, considering we also want to support more complex cases such as 2D tiled microscopy images.

**Comment by benarnon8** [comment]
So I managed to solve it, not ideal and foolproof, but it handles to source of the issue.

To collect the source files I used `glob`, which collects according to the arbitrary-looking filesystem appearance ([source](https://stackoverflow.com/questions/6773584/how-is-pythons-glob-glob-ordered)).

It was solved using `sorted` and `reverse`:
`image_files = sorted(series_dir.glob("*"), reverse=True)`

When time allows I'll try to implement using the `order_datasets` function, but for now sorting the files is good enough.
And in case I find other bugs I'll create another issue or pull request.

You can close the issue or implement the ordering verification function for the next version first.

I thank you all again, I really appreciate the time and effort!

**Comment by CPBridge** [comment]
Glad it's working @benarnon8 ! I would recommend ordering spatially using a function like I did because filesystem globbing is bound to break at some point.

To be clear for those who may stumble across this issue in the future: you can currently (highdicom 0.10.0) pass the source images and corresponding mask frames in *any order* and the constructor will sort this all out for you. They do not need to be ordered spatially. However the order *does* need to match between the two lists, i.e. `pixel_array[i, ...]` is the segmentation of `source_images[i]`.

**Comment by benarnon8** [comment]
My motivation is to combine volumetric MRI scan that I get from a radiologist as a DICOM file, with an AI generated segmentation (let's say as np.array).
So the main issue is that I can't easily align them or change the mask/source without getting the z-axis position, and that's the reason I want to still implement an automated solution that is independent of the file order.
The ordering function is a good way to do that and I will definitely write it somewhere in my code, but if you have time I think it's generally a good option to put into the library so it's less dependent on the user.
I hope I'll be able to do it by the end of the week, and if so I'll send you my code in case you want to push it.
