### ISSUE TITLE
get_plane_positions_of_image returns list of pydicom.Sequence instead of highdicom.PlanePositionSequence

### ISSUE THREAD

**Issue by thomas-albrecht** [ImagingDataCommons/highdicom#231]
The function [`get_plane_positions_of_image`](https://github.com/ImagingDataCommons/highdicom/blob/master/src/highdicom/seg/content.py#L459) specifies that it should return a `List[PlanePositionSequence]`. Instead, the call [`item.PlanePositionSequence`](https://github.com/ImagingDataCommons/highdicom/blob/master/src/highdicom/seg/content.py#L459) causes the return of a `List[pydicom.Sequence]`. 

That sequence has the name PlanePositionSequence but it is no instance of the class `highdicom.PlanePositionSequence`, which later can cause the error ["Can only compare instances of PlanePositionSequence"](https://github.com/ImagingDataCommons/highdicom/blob/b1ccd3e46a5fda77859b6d9211ce054212f57da2/src/highdicom/content.py#L470) when comparing plane positions in the [seg/sop.py](https://github.com/ImagingDataCommons/highdicom/blob/b1ccd3e46a5fda77859b6d9211ce054212f57da2/src/highdicom/seg/sop.py#LL1406C33-L1406C33) file. 

I am planning to submit a merge request to fix this by using the function [`highdicom.PlanePositionSequence.from_sequence`](https://github.com/ImagingDataCommons/highdicom/blob/b1ccd3e46a5fda77859b6d9211ce054212f57da2/src/highdicom/content.py#L497) to convert the `pydicom.Sequence` to a `highdicom.PlanePositionSequence`.

**Comment by CPBridge** [comment]
Thanks @thomas-albrecht I look forward to receiving your PR
