### ISSUE TITLE
Request for ReferencedSeriesUID accessor 

### ISSUE THREAD

**Issue by DanielaSchacherer** [ImagingDataCommons/highdicom#283]
As discussed with Chris today, it would add value if - especially for the class highdicom.sr.Comprehensive3DSR - it would be possible to access all the series referenced in the sr with a getter function. 

This would eliminate the need to go through the pydicom interface like: sr.CurrentRequestedProcedureEvidenceSequence[0].ReferencedSeriesSequence[0].SeriesInstanceUID.

**Comment by CPBridge** [comment]
Resolved in #303
